### ISSUE TITLE
Is there a way to run just MAML + FT ? without using the SS paramaters

### ISSUE THREAD

**Issue by sudarshan1994** [yaoyao-liu/meta-transfer-learning#11]
I wanted to know if I can run just update the update the pre-trained weights (and not the SS parameters ) during the outer loop of the MAML algorithm and update just the linear layer in the inner loop ?

**Comment by sudarshan1994** [comment]
Thanks a lot for releasing your code

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

If you'd like to use the standard ResNet instead of the ResNet with MTL, you may change the following line:
https://github.com/yaoyao-liu/meta-transfer-learning/blob/b08aa8b3a7d15a396a8ae1af311806aa398c90d0/pytorch/models/mtl.py#L52
to
```python
self.encoder = ResNetMtl(mtl=False)
```

**Comment by sudarshan1994** [comment]
Thanks for your quick response
