### ISSUE TITLE
resnet model not consistant between pytorch and tensorflow

### ISSUE THREAD

**Issue by leon-liangwu** [yaoyao-liu/meta-transfer-learning#32]
I find that the ResNet models of PyTorch version and TensorFlow version are different. 
Is that right? What is the performance of the PyTorch version?

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.
We use the TensorFlow version for the experiments in the paper.
PyTorch version is a re-implementation based on [this repo](https://github.com/Sha-Lab/FEAT). So some details are different from the original TensorFlow version.

For the performance of the PyTorch version, you may refer to [this issue](https://github.com/yaoyao-liu/meta-transfer-learning/issues/5).

**Comment by leon-liangwu** [comment]
Thanks for your reply very much.
Have you ever tested the same architecture from your TensorFlow version in PyTorch?
What is that performance?

**Comment by yaoyao-liu** [comment]
Currently, we don't have the PyTorch results for other backbones.

If you hope to re-implement the architecture (ResNet-12), you may follow [this repo](https://github.com/kjunelee/MetaOptNet).

We plan to update other backbones (ResNet-12, WRN-28-10) later.

**Comment by leon-liangwu** [comment]
OK. Thanks for your information.
