### ISSUE TITLE
how to get the code about Hard Task Meta-Batch?

### ISSUE THREAD

**Issue by Wiikk** [yaoyao-liu/meta-transfer-learning#36]
Hi, thanks for your excellent work!
Could you please release the code about Hard Task Meta-Batch?
I am eager to see it! Thank you!

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work!
I'll merge the implementation for hard task meta-batch later. I'll keep you informed when it is updated.

**Comment by Wiikk** [comment]
That's great!! Thanks for your kind help.

**Comment by Wiikk** [comment]
Hi, sorry to bother you again, could you give an approximate time for the code update?

**Comment by yaoyao-liu** [comment]
Hi @Wiikk,

As I am working on another project now, I am sorry that it might take several months for me to update this repository. Thanks a lot for your interest and patient.

**Comment by Wiikk** [comment]
Ok, thank you for your timely reply!

**Comment by Daniel123jia** [comment]
> Hi @Wiikk,
> 
> As I am working on another project now, I am sorry that it might take several months for me to update this repository. Thanks a lot for your interest and patient.

If you don't want to update please don't lie to us

**Comment by yaoyao-liu** [comment]
Hi @Daniel123jia,

Thanks for your interest in our work. I am sorry that I didn't update this GitHub repository on time. I have to say, currently, I cannot guarantee a deadline to update this repository. 

If you have any difficulties using my project, please contact me via email: yliu538@jhu.edu
I can share our original code with you. I hope this can help to apply our method to your work. If you have any further questions, I am also very happy to discuss them. 

Best regards,

Yaoyao

**Comment by Daniel123jia** [comment]
Dear Yaoyao:

       Could you please share the original code (about Meta-Transfer Learning through Hard Tasks) with me? Thank you very much. Wish you a happy life and work.













At 2023-09-13 11:19:55, "Yaoyao Liu" ***@***.***> wrote:

Hi @Daniel123jia,

Thanks for your interest in our work. I am sorry that I didn't update this GitHub repository on time. I have to say, currently, I cannot guarantee a deadline to update this repository.

If you have any difficulties using my project, please contact me via email: ***@***.***
I can share our original code with you. I hope this can help to apply our method to your work. If you have any further questions, I am also very happy to discuss them.

Best regards,

Yaoyao

**Comment by yaoyao-liu** [comment]
Hi @Daniel123jia,

Could you please directly send your email to yliu538@jhu.edu? Thank you so much! It seems that you replied to my email using the GitHub system, and I still cannot see your email address.

Looking forward to hearing from you soon!

Best regards,

Yaoyao
