### ISSUE TITLE
meta batch size (number of episodes) always equal to 1

### ISSUE THREAD

**Issue by DanqingZ** [yaoyao-liu/meta-transfer-learning#43]
Hi for the data loader, I found the meta batch size is not configurable and always set to 1 for this code base. And because meta batch = 1, multi gpu won't work by simply adding model = nn.DataParallel(model).
for example
https://github.com/yaoyao-liu/meta-transfer-learning/blob/main/pytorch/trainer/meta.py#L144-L149
the size of data_shot: [N_way * N_shot, 3, image_size, image_size]
the size of data_query: [N_way * N_query, 3, image_size, image_size]
the ideal should be:
the size of data_shot: [N_episode, N_way * N_shot, 3, image_size, image_size]
the size of data_query: [N_episode, N_way * N_query, 3, image_size, image_size]

Thanks, please correct me if I am wrong, thanks.

**Comment by yaoyao-liu** [comment]
If you hope to run this project on multiple GPUs, you may revise the code following [this project](https://github.com/icoz69/DeepEMD). It provides a multi-GPU option. 

Our PyTorch implementations are both based on [FEAT](https://github.com/Sha-Lab/FEAT).

**Comment by DanqingZ** [comment]
@yaoyao-liu thanks for pointing me to the codebase! 
one more question here: https://github.com/yaoyao-liu/meta-transfer-learning/blob/main/pytorch/dataloader/dataset_loader.py#L56
why did you set image_size = 80? The other implementations set image_size = 80.

**Comment by yaoyao-liu** [comment]
> @yaoyao-liu thanks for pointing me to the codebase!
> one more question here: https://github.com/yaoyao-liu/meta-transfer-learning/blob/main/pytorch/dataloader/dataset_loader.py#L56
> why did you set image_size = 80? The other implementations set image_size = 80.

For this part, I follow FEAT:
https://github.com/Sha-Lab/FEAT/blob/5ffadb7000a4c9cb47e6d9ca7062964f5e05ffdf/feat/dataloader/mini_imagenet.py#L50

**Comment by DanqingZ** [comment]
I see, thanks.
