### ISSUE TITLE
Performance Pytorch Version

### ISSUE THREAD

**Issue by mikehuisman** [yaoyao-liu/meta-transfer-learning#46]
Hi Yaoyao,

In your repository, it says that the pytorch performance is under check. Do you have any update on this?

Kind regards,

Mike Huisman

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

Could you please try the pre-train model/code in [this project](https://github.com/icoz69/DeepEMD)?
We're using a similar pre-training strategy. So that we can find which part is incorrect.

**Comment by yaoyao-liu** [comment]
I have tested the current code. The performance is around 59%-61%. It shouldn't be that low. Related issue: [link](https://github.com/yaoyao-liu/meta-transfer-learning/issues/5)

**Comment by mikehuisman** [comment]
Thank you for your prompt response!
Yesterday, I reinstalled the environment, re-downloaded all data sets, updated CUDA drivers, and now I indeed get the same results!
Thank you for your help.
