### ISSUE TITLE
FC-100 data loader

### ISSUE THREAD

**Issue by YoungBigBird1985** [yaoyao-liu/meta-transfer-learning#47]
I have found out the FC-100 data from links of your paper, and Could you please share the data loader and detailed setting for FC-100 experiments?

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work. 
You may directly change the data directories in [this file](https://github.com/yaoyao-liu/meta-transfer-learning/blob/main/tensorflow/run_experiment.py) to run the experiments on FC100.
If there are any further questions, please let me know.

Best,
Yaoyao

**Comment by YoungBigBird1985** [comment]
Hi Liu, I want to run your code on CIFAR-FS, which has a 32* 32* 3 shape of Image, and cannot fit to your code. I try to change the parameter img_size from 84 to 32, but it has error with  "Negative dimension size caused by subtracting 5 from 2 for 'pretrain-model/AvgPool' (op: 'AvgPool') with input shapes: [64,2,2,512]". Please help address this issue.

**Comment by yaoyao-liu** [comment]
I have replyed to you in [this issue](https://github.com/yaoyao-liu/meta-transfer-learning/issues/50).

**Comment by YoungBigBird1985** [comment]
thanks
