### ISSUE TITLE
Data Loader for CIFAR-FS

### ISSUE THREAD

**Issue by YoungBigBird1985** [yaoyao-liu/meta-transfer-learning#50]
Hi Liu, I want to run your code on CIFAR-FS, which has a 32* 32* 3 shape of Image, and cannot fit to your code. I try to change the parameter img_size from 84 to 32, but it has error with "Negative dimension size caused by subtracting 5 from 2 for 'pretrain-model/AvgPool' (op: 'AvgPool') with input shapes: [64,2,2,512]". Please help address this issue.

The data is downloaded from http://www.cs.toronto.edu/~kriz/

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

If you hope to run the code on CIFAR-FS, I suggest you resize the images to `84x84`. This pre-processing is applied in many related papers, e.g., <https://git.io/JOZI8>.

Best,
Yaoyao

**Comment by YoungBigBird1985** [comment]
thanks.

**Comment by YoungBigBird1985** [comment]
thanks.
