### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by Lcance** [yaoyao-liu/meta-transfer-learning#61]
My work environment is windows, and I download the mini-imagenet data from Google Drive(The website is https://drive.google.com/file/d/1vv3m14kusJcRpCsG-brG_Xk9MnetY9Bt/view ).  Then I unzip the file in Windows cmd.

I run the pretrain phase using _python run_pre.py_, but get a valueError: max() arg is an empty sequence, I think there is nothing wrong. Could you help me to fix it?

Now here is my oroject architecture.
├── data         
 |   ├── mini
 |       ├── test  
 |           └── test .csv  
 |       ├── train  
 |           └── train .csv  
 |       ├── val  
 |           └── val .csv  
├── data_generator              
 |   ├── dataset_loader.py       
 |   └── meta_data_generator.py  
├── models                      
 |   ├── mtl.py                  
 |   ├── resnet_mtl.py           
 |   └── conv2d_mtl.py           
├── trainer                     
 |   ├── pre.py                 
 |   └── meta.py                 
├── utils                       
 |   ├── gpu_tools.py            
 |   └── misc.py                 
├── main.py                     
├── run_pre.py                  
└── run_meta.py                 

**Here are my Parameters：**
{'base_lr': 0.01,
 'dataset': 'MiniImageNet',
 'dataset_dir': './data/mini/',
 'eval_weights': None,
 'gamma': 0.5,
 'gpu': '0',
 'init_weights': None,
 'max_epoch': 100,
 'meta_label': 'exp1',
 'meta_lr1': 0.0001,
 'meta_lr2': 0.001,
 'model_type': 'ResNet',
 'num_batch': 100,
 'phase': 'pre_train',
 'pre_batch_size': 128,
 'pre_custom_momentum': 0.9,
 'pre_custom_weight_decay': 0.0005,
 'pre_gamma': 0.2,
 'pre_lr': 0.1,
 'pre_max_epoch': 110,
 'pre_step_size': 30,
 'seed': 0,
 'shot': 1,
 'step_size': 10,
 'train_query': 15,
 'update_step': 50,
 'val_query': 15,
 'way': 5}
Using gpu: 0
Using random seed.

**Here is the error:**
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    trainer = PreTrainer(args)
  File "C:\Users\Lan\Desktop\meta-transfer-learning-main\pytorch\trainer\pre.py", line 49, in __init__
    self.val_sampler = CategoriesSampler(self.valset.label, 600, self.args.way, self.args.shot + self.args.val_query)
  File "C:\Users\Lan\Desktop\meta-transfer-learning-main\pytorch\dataloader\samplers.py", line 24, in __init__
    for i in range(max(label) + 1):
ValueError: max() arg is an empty sequence

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

According to your log, it seems that you are running the code on a Windows PC. I only tested the code on Debian/Unbuntu. If you need to run the code using Windows, you may need to adjust some parts of the code accordingly. For example, you need to update the following directory to the Windows format:
https://github.com/yaoyao-liu/meta-transfer-learning/blob/31e51e3ed45281c0cddb1af005249c9d1029fb18/pytorch/main.py#L26

I recommend you run the code on a server with the Debian/Ubuntu system and a GPU, e.g., NVIDIA V100.

**Comment by Lcance** [comment]
Hi, thanks for your quick reply and thanks to your code, Yao Shen. My confusion seemed to have been cleared. It is because I forgot to unzip the data.

And When I test the code on Pytorch1.10.0, there is another UserWarning:Detected call of `lr_scheduler.step()` before `optimizer.step()`.
The reason is that: In PyTorch 1.1.0 and later, we should call them in the opposite order: optimizer.step() before lr_scheduler.step(). Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.

I found the solution : IN the file  ** meta.py** 
the code  _self.lr_scheduler.step()_  in Line 131 need to be moved to Line234(eg), because the  steps need to  be adjusted

IF anyone have the same question, they can refer to this.
