### ISSUE TITLE
Question about ResNet-12 in Pytorch code

### ISSUE THREAD

**Issue by cyvius96** [yaoyao-liu/meta-transfer-learning#8]
Hello,

Thanks for your impressive work and sharing the code.

I am having a question about ResNet-12 in Pytorch's code:
https://github.com/yaoyao-liu/meta-transfer-learning/blob/e98971bbeb7dec0f07af36b698ab7816c4e7ae3f/pytorch/models/resnet_mtl.py#L173

The channels (80,160,320,640) and the structure is different to the paper

> It contains 4 residual blocks and each block has 3 CONV layers
with 3 × 3 kernels. At the end of each residual block, a
2 × 2 max-pooling layer is applied. The number of filters
starts from 64 and is doubled every next block.

I am wondering if my understanding is correct, and what leads to the designing choice of the backbone?

Thank you!

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.
The TensorFlow version is the original code we use for the paper, so ResNet-12 is provided in the TensorFlow version.

For PyTorch version, we directly implement our method based on the framework of [FEAT](https://github.com/Sha-Lab/FEAT), so I use the backbone provided in that repo.

If you would like to run experiments based on ResNet-12 using PyTorch, you could change the network hyperparameters yourself. I also welcome you to commit the ResNet-12 for the PyTorch version if you have time. :)

**Comment by cyvius96** [comment]
I see. Thanks for your response!
